#!/bin/bash
# AWS Connection
 curl  --insecure  -X POST https://localhost/api/v1.3/vfm/aws/connections  -u admin:i-0b35ce3e20eed248b  -d '{"id": "", "alias": "AWS-Cred","authType": "basicCredentials","regionName": "us-east-1","vpcId": "vpc-a9e7cfd1","availabilityZone": "us-east-1a","accessKey": "AKIAJHTUIWCEVO7WZM4A","secretKey": "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"}' --header "Content-Type:application/json"
# Launching G-vTAP Controller Configuration
 d=`curl -s  --insecure   -u admin:i-0b35ce3e20eed248b 'https://localhost/api/v1.3/vfm/aws/connections' | grep  "id"  | cut -d ":" -f2 | tr -d "\"," | tr -d  " "`
 curl  --insecure -X POST https://localhost/api/v1.3/vfm/aws/fabricDeployment/gvTapControllers/configs  -u admin:i-0b35ce3e20eed248b -d '{ "id": "", "connId": "${d}", "connAlias": "AWS-Cred", "imageId": "ami-13e2ec04", "imageName": "gigamon-gvtap-cntlr-1.2-1",  "instanceType": "t2.medium",  "ebsVolumeType": "gp2", "sshKeyPairName": "gigakeypair", "mgmtSubnetSpec": {  "subnetId": "subnet-edc34bb0", "subnetName": "gigamon-visibilitysubnet",  "securityGroups": [{ "securityGroupId": "sg-9a11b5ee",  "securityGroupName": "gigamon-nsg" } ] }, "usePublicIps": false,"numOfInstancesToLaunch": 1,"mtu": 9001}' --header "Content-Type:application/json"
# data="{ \"id\": \"\", \"connId\": \"${d}\", \"connAlias\": \"AWS-Cred\", \"imageId\": \"ami-13e2ec04\", \"imageName\": \"gigamon-gvtap-cntlr-1.2-1\", \"instanceType\": \"t2.medium\", \"ebsVolumeType\": \"gp2\", \"sshKeyPairName\": \"gigakeypair\", \"mgmtSubnetSpec\": { \"subnetId\": \"subnet-edc34bb0\", \"subnetName\": \"gigamon-visibilitysubnet\", \"securityGroups\": [{ \"securityGroupId\": \"sg-9a11b5ee\", \"securityGroupName\": \"gigamon-nsg\" } ] }, \"usePublicIps\": false,\"numOfInstancesToLaunch\": 1,\"mtu\": 9001}"
# curl  --insecure -X POST https://localhost/api/v1.3/vfm/aws/fabricDeployment/gvTapControllers/configs  -u admin:i-0b35ce3e20eed248b -d "$data"  --header "Content-Type:application/json"
# Launching V Series Controller Configuration
 curl  --insecure -X POST https://localhost/api/v1.3/vfm/aws/fabricDeployment/vseriesControllers/configs  -u admin:i-0b35ce3e20eed248b -d '{ "id": "", "connId": "$d", "connAlias": "AWS-Cred","platform": "aws", "imageId": "ami-b44a7acf", "imageName": "gigamon-gigavue-vseries-cntlr-1.2-1",  "instanceType": "t2.medium",  "ebsVolumeType": "gp2", "sshKeyPairName": "gigakeypair", "mgmtSubnetSpec": {  "subnetId": "subnet-edc34bb0", "subnetName": "gigamon-visibilitysubnet",  "securityGroups": [{ "securityGroupId": "sg-9a11b5ee",  "securityGroupName": "gigamon-nsg" } ] }, "usePublicIps": false,"numOfInstancesToLaunch": 1}' --header "Content-Type:application/json"
# data1="{ \"id\": \"\", \"connId\": \"$d\", \"connAlias\": \"AWS-Cred\",\"platform\": \"aws\", \"imageId\": \"ami-b44a7acf\", \"imageName\": \"gigamon-gigavue-vseries-cntlr-1.2-1\", \"instanceType\": \"t2.medium\", \"ebsVolumeType\": \"gp2\", \"sshKeyPairName\": \"gigakeypair\", \"mgmtSubnetSpec\": { \"subnetId\": \"subnet-edc34bb0\", \"subnetName\": \"gigamon-visibilitysubnet\", \"securityGroups\": [{ \"securityGroupId\": \"sg-9a11b5ee\", \"securityGroupName\": \"gigamon-nsg\" } ] }, \"usePublicIps\": false,\"numOfInstancesToLaunch\": 1}"
# curl  --insecure -X POST https://localhost/api/v1.3/vfm/aws/fabricDeployment/vseriesControllers/configs  -u admin:i-0b35ce3e20eed248b -d "$data1"  --header "Content-Type:application/json"
# Launching V Series Node Configuration
 curl  --insecure -X POST https://localhost/api/v1.3/vfm/aws/fabricDeployment/vseriesNodes/configs  -u admin:ii-0b35ce3e20eed248b -d '{"id": "", "connAlias": "AWS-Cred","connId": "37c47841-0158-4743-92d1-212ae1f2c795","platform": "aws","imageId": "ami-fd417186","imageName": "gigamon-gigavue-vseries-node-1.2-1",  "sshKeyPairName": "gigakeypair", "mgmtSubnetSpec": { "subnetId": "subnet-314dc36c",  "subnetName": "gigamon-subnet1","securityGroups": [  {  "securityGroupId": "sg-33f92647", "securityGroupName": "Gigamon Visibility Platform for AWS-GigaVUE-FM for AWS 5-1-AutogenByAWSMP-1" } ] }, "minInstancesToLaunch": 1, "maxInstancesToLaunch": 1, "mtu": 9001, "ebsVolumeType": "gp2","tunnelSubnetsSpec": [ { "subnetId": "subnet-314dc36c", "subnetName": "gigamon-subnet1", "securityGroups": [{ "securityGroupId": "sg-33f92647",  "securityGroupName": "Gigamon Visibility Platform for AWS-GigaVUE-FM for AWS 5-1-AutogenByAWSMP-1"  } ]}],"dataSubnetsSpec": [{ "subnetId": "subnet-314dc36c", "subnetName": "gigamon-subnet1", "securityGroups": [{"securityGroupId": "sg-33f92647", "securityGroupName": "Gigamon Visibility Platform for AWS-GigaVUE-FM for AWS 5-1-AutogenByAWSMP-1"}]}],"instanceType": "c4.large"}' --header "Content-Type:application/json" 
# data2="{\"id\": \"\", \"connAlias\": \"AWS-Cred\",\"connId\": \"${d}\",\"platform\": \"aws\",\"imageId\": \"ami-fd417186\",\"imageName\": \"gigamon-gigavue-vseries-node-1.2-1\",  \"sshKeyPairName\": \"gigakeypair\", \"mgmtSubnetSpec\": { \"subnetId\": \"subnet-edc34bb0\",  \"subnetName\": \"gigamon-visibilitysubnet\",\"securityGroups\": [  {  \"securityGroupId\": \"sg-9a11b5ee\", \"securityGroupName\": \"gigamon-nsg\" } ] }, \"minInstancesToLaunch\": 1, \"maxInstancesToLaunch\": 1, \"mtu\": 9001, \"ebsVolumeType\": \"gp2\",\"tunnelSubnetsSpec\": [ { \"subnetId\": \"subnet-86dd55db\", \"subnetName\": \"gigamon-toolsubnet\", \"securityGroups\": [{ \"securityGroupId\": \"sg-9a11b5ee\",  \"securityGroupName\": \"gigamon-nsg\"  } ]}],\"dataSubnetsSpec\": [{ \"subnetId\": \"subnet-49c64e14\", \"subnetName\": \"gigamon-appsubnet\", \"securityGroups\": [{\"securityGroupId\": \"sg-9a11b5ee\", \"securityGroupName\": \"gigamon-nsg\"}]}],\"instanceType\": \"c4.large\"}"
 # curl  --insecure -X POST https://localhost/api/v1.3/vfm/aws/fabricDeployment/vseriesNodes/configs  -u admin:i-0b35ce3e20eed248b -d "$data2"  --header "Content-Type:application/json"
 
  